server:
  name: violin-scheduler
  addr: "0.0.0.0:8080"

zap:
  debugFileName: "C:\\log\\violin-scheduler\\debug.log"
  infoFileName: "C:\\log\\violin-scheduler\\info.log"
  warnFileName: "C:\\log\\violin-scheduler\\warn.log"
  maxSize: 500
  maxAge: 28
  maxBackups: 3

scheduler:
  pod:
    namespace: "test"
    selectorLabel:
      key: "violin-scheduler-pod"
      value: "violin-scheduler"
  node:
    selectorLabel: "violin-scheduler-node"
  zone:
    selectorLabel: "violin-scheduler-zone"
